global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'customer-service:8080'
          - 'billing-service:8080'
          - 'delivery-service:8080'
          - 'address-validation-service:8080'
